### ISSUE TITLE
JsSIP(0.7.4) - deprecated 'addStream()'

### ISSUE THREAD

**Issue by tiagoesteves7** [turbobridge/WebCall#3]
Good afternoon, I am developing a project in which I followed your repository, and when validating the audio, I received an error stating that there is a deprecated function 'addStream()' in the jsSIP version (0.7.4). Is there any possibility of providing an update or sending an example to better understand the functionality?

**Comment by rshpount** [comment]
This library is out of date and deprecated. Please contact support@turbobridge.com for the newer library version.
